/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.pswdcomponente;

import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author alumnadotarde
 */
public class MedidorPswdJPanel extends javax.swing.JPanel {

    private final MedidorPswd mp;
    private final String[] mensajeEval;

    /**
     * Creates new form MedidorPswdJPanel
     */
    public MedidorPswdJPanel() {
        initComponents();
        mp = new MedidorPswd();
        mensajeEval = new String[]{
            "Inválida",
            "Muy débil",
            "Débil",
            "Media",
            "Buena",
            "Fuerte",
            "Muy fuerte",
            "Excelente"
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordFieldPswd = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jProgressBarEval = new javax.swing.JProgressBar();
        jLabelEval = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(2, 0, 10, 10));

        jPanel1.setLayout(new java.awt.GridLayout(3, 0, 5, 10));

        jLabel1.setText("Introduce tu contraseña para comprobar su fortaleza:");
        jPanel1.add(jLabel1);

        jPasswordFieldPswd.setText("jPasswordField1");
        jPasswordFieldPswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPswdActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordFieldPswd);

        jPanel2.setLayout(new java.awt.GridLayout(2, 0, 0, 5));
        jPanel2.add(jProgressBarEval);

        jLabelEval.setText("Tu contraseña actual es inválida.");
        jPanel2.add(jLabelEval);

        jPanel1.add(jPanel2);

        add(jPanel1);

        jLabel2.setText("jLabel2");
        add(jLabel2);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldPswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPswdActionPerformed

    }//GEN-LAST:event_jPasswordFieldPswdActionPerformed

    private void evaluar(String paswd) {
        int eval = mp.medir(paswd);
    }

    private void actualizarBarraProgreso(int eval) {
        jProgressBarEval.setValue(eval);
        jProgressBarEval.setForeground(switch (eval) {
            case 1, 2 ->
                java.awt.Color.RED;
            case 3, 4 ->
                java.awt.Color.YELLOW;
            case 5, 6 ->
                java.awt.Color.GREEN;
            case 7 ->
                java.awt.Color.BLUE;
            default ->
                java.awt.Color.GRAY;
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEval;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldPswd;
    private javax.swing.JProgressBar jProgressBarEval;
    // End of variables declaration//GEN-END:variables
}
