/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.botonoptions;

import javax.swing.JOptionPane;

/**
 *
 * @author alumnadotarde
 */
public class PantallaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName());

    /**
     * Creates new form prueba
     */
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBotonMensaje = new javax.swing.JButton();
        jBotonConfirmacion = new javax.swing.JButton();
        jBotonEntrada = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBotonMensaje.setText("Mensaje");
        jBotonMensaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonMensajeActionPerformed(evt);
            }
        });

        jBotonConfirmacion.setText("Confirmación");
        jBotonConfirmacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonConfirmacionActionPerformed(evt);
            }
        });

        jBotonEntrada.setText("Entrada");
        jBotonEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonEntradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(jBotonMensaje)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jBotonEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(jBotonConfirmacion)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jBotonMensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonConfirmacion)
                    .addComponent(jBotonEntrada))
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonMensajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonMensajeActionPerformed
        JOptionPane.showMessageDialog(this, "Un mensaje de prueba", "Título", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jBotonMensajeActionPerformed

    private void jBotonConfirmacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonConfirmacionActionPerformed
        int resultado = JOptionPane.showConfirmDialog(this, "¿Quieres borrar el mensaje?", "Título de confirmación", JOptionPane.YES_NO_OPTION);
        if (resultado == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Se ha borrado correctamente", "Título de borrado", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Borrado cancelado", "Título de odarrob", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBotonConfirmacionActionPerformed

    private void jBotonEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonEntradaActionPerformed
        String nombre = JOptionPane.showInputDialog(this, "Introduce tu nombre", "¿Cómo te llamas?", JOptionPane.QUESTION_MESSAGE);
        JOptionPane.showMessageDialog(this, "Hola, ".concat(nombre), "Bienvenido", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jBotonEntradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonConfirmacion;
    private javax.swing.JButton jBotonEntrada;
    private javax.swing.JButton jBotonMensaje;
    // End of variables declaration//GEN-END:variables
}
