/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package JPanelEvaluacionPassword;

import java.io.Serializable;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Insets;
import javax.swing.JComponent;
import javax.swing.plaf.basic.BasicProgressBarUI;
// removed unused import java.util.Arrays; password is read directly from the field

/**
 *
 * @author alumnadotarde
 */
public class MedidorPswdJPanel extends javax.swing.JPanel implements Serializable {

    private final MedidorPswd mp;
    private final String[] mensajeEval;

    /**
     * Creates new form MedidorPswdJPanel
     */
    public MedidorPswdJPanel() {
        initComponents();
        mp = new MedidorPswd();
        mensajeEval = new String[]{
            "Inválida",
            "Muy débil",
            "Débil",
            "Regular",
            "Buena",
            "Fuerte",
            "Muy fuerte",
            "Excelente"
        };
        // Make the progress bar use the same scale as the evaluator (0..7)
        jProgressBarEval.setMinimum(0);
        jProgressBarEval.setMaximum(7);
        // Hide the percent text; we'll paint the bar itself with a custom UI
        jProgressBarEval.setStringPainted(false);

        // Update evaluation as the user types: listen to document changes
        jPasswordFieldPswd.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                evaluar(new String(jPasswordFieldPswd.getPassword()));
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                evaluar(new String(jPasswordFieldPswd.getPassword()));
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                evaluar(new String(jPasswordFieldPswd.getPassword()));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPasswordFieldPswd = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jProgressBarEval = new javax.swing.JProgressBar();
        jPanel4 = new javax.swing.JPanel();
        jLabelTuContra = new javax.swing.JLabel();
        jLabelEval = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelLength = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(2, 0, 10, 10));

        jPanel1.setLayout(new java.awt.GridLayout(3, 0, 5, 10));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Introduce tu contraseña para comprobar su fortaleza.");
        jPanel1.add(jLabel1);

        jPasswordFieldPswd.setAutoscrolls(false);
        jPasswordFieldPswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldPswdActionPerformed(evt);
            }
        });
        jPanel1.add(jPasswordFieldPswd);

        jPanel2.setLayout(new java.awt.GridLayout(2, 0, 0, 5));

        jProgressBarEval.setOpaque(true);
        jPanel2.add(jProgressBarEval);

        jPanel4.setLayout(new java.awt.GridLayout(1, 4, 4, 0));

        jLabelTuContra.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelTuContra.setText("Tu contraseña es");
        jPanel4.add(jLabelTuContra);

        jLabelEval.setText("inválida.");
        jPanel4.add(jLabelEval);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Longitud:");
        jPanel4.add(jLabel8);

        jLabelLength.setText("0");
        jPanel4.add(jLabelLength);

        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2);

        add(jPanel1);

        jLabel3.setText(" Requisitos:");

        jLabel4.setText(" - La longitud de la contraseña debe de ser 5 como mínimo.");

        jLabel5.setText(" Recomendaciones:");

        jLabel6.setText(" - Combinar minúsculas, mayúsculas, números  y carácteres especiales.");

        jLabel7.setText(" - Cuánto más larga sea la contraseña, mejor.");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        add(jPanel3);
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordFieldPswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldPswdActionPerformed
        // Use the actual password content rather than Arrays.toString(...) which
        // returns a bracketed, comma-separated representation of the char array.
        evaluar(new String(jPasswordFieldPswd.getPassword()));
    }//GEN-LAST:event_jPasswordFieldPswdActionPerformed

    private void evaluar(String paswd) {
        int eval = mp.medir(paswd);
        actualizarBarraProgreso(eval);
        actualizarMensaje(eval);
        actualizarLongitud(paswd);
    }

    private void actualizarBarraProgreso(int eval) {
        jProgressBarEval.setValue(eval);
        // Choose a color for the bar fill based on evaluation
        Color fill = switch (eval) {
            case 1, 2 ->
                Color.RED;
            case 3, 4 ->
                Color.YELLOW;
            case 5, 6 ->
                Color.GREEN;
            case 7 ->
                Color.CYAN;
            default ->
                Color.GRAY;
        };
        // Apply a simple custom UI so the bar's filled area uses the chosen color
        jProgressBarEval.setUI(new ColorProgressBarUI(fill));
    }

    private void actualizarMensaje(int eval) {
        jLabelEval.setText(mensajeEval[eval].toLowerCase() + ".");
    }
    
    private void actualizarLongitud(String pswd) {
        jLabelLength.setText(pswd.length() + "");
    }

    /**
     * A tiny ProgressBarUI that paints the filled portion using a fixed color.
     * This ensures the bar itself (not the string) changes color regardless of
     * LAF.
     */
    private static class ColorProgressBarUI extends BasicProgressBarUI {

        private final Color fillColor;

        ColorProgressBarUI(Color fillColor) {
            this.fillColor = fillColor;
        }

        @Override
        protected void paintDeterminate(Graphics g, JComponent c) {
            Insets b = progressBar.getInsets();
            int barWidth = progressBar.getWidth() - (b.left + b.right);
            int barHeight = progressBar.getHeight() - (b.top + b.bottom);

            // Paint background
            g.setColor(progressBar.getBackground());
            g.fillRect(b.left, b.top, barWidth, barHeight);

            // Determine filled width
            double pc = progressBar.getPercentComplete();
            // Clamp percent to [0,1]
            if (Double.isNaN(pc) || pc < 0d) {
                pc = 0d;
            } else if (pc > 1d) {
                pc = 1d;
            }
            int fillWidth = (int) Math.round(barWidth * pc);

            // Paint filled portion with desired color
            g.setColor(fillColor);
            g.fillRect(b.left, b.top, fillWidth, barHeight);

            // Optional: paint a simple border
            g.setColor(Color.DARK_GRAY);
            g.drawRect(b.left, b.top, barWidth - 1, barHeight - 1);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelEval;
    private javax.swing.JLabel jLabelLength;
    private javax.swing.JLabel jLabelTuContra;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordFieldPswd;
    private javax.swing.JProgressBar jProgressBarEval;
    // End of variables declaration//GEN-END:variables
}
