// Eliminado comentario de plantilla NetBeans
package com.mycompany.proyectotarea1;

import java.io.File;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 * Ventana principal del juego tipo "clicker". Gestiona el contador, las mejoras
 * y abre las demás pantallas (estadísticas, ayuda y compras). Proporciona la
 * lógica de producción activa (clic) y pasiva (cps).
 *
 * @author Samii de las Heras Cózar
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    private final long cronoInicio;
    private int cont = 0;
    private int producitividad = 0;
    private int hornos = 0;
    private int fabricas = 0;
    private int cps = 0;
    private int resets = 0;

    private javax.swing.Timer Timer;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName());

    /**
     * Crea la ventana principal e inicializa la interfaz y el cronómetro.
     */
    public PantallaPrincipal() {
        // use a striped orange background as the content pane before initializing components
        setContentPane(new BgPanel());
        initComponents();
        cronoInicio = System.currentTimeMillis();
        jLabelCont.setText(this.getCont() + "");
        setClickerImage("Galletas");
        producir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonReset1 = new javax.swing.JButton();
        jLabelClicker = new javax.swing.JLabel();
        jLabelUnidad = new javax.swing.JLabel();
        jComboBoxUnidad = new javax.swing.JComboBox<>();
        jButtonStats = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jButtonMejoras = new javax.swing.JButton();
        jLabelCont = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAyuda = new javax.swing.JButton();

        jButtonReset1.setBackground(new java.awt.Color(255, 150, 200));
        jButtonReset1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonReset1.setForeground(new java.awt.Color(255, 250, 100));
        jButtonReset1.setText("Restablecer");
        jButtonReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReset1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelClicker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelClickerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelClickerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelClickerMouseExited(evt);
            }
        });

        jLabelUnidad.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabelUnidad.setText("Galletas");

        jComboBoxUnidad.setBackground(new java.awt.Color(255, 150, 200));
        jComboBoxUnidad.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jComboBoxUnidad.setForeground(new java.awt.Color(255, 250, 100));
        jComboBoxUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Galletas", "Pizzas", "Tartas" }));
        jComboBoxUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUnidadActionPerformed(evt);
            }
        });

        jButtonStats.setBackground(new java.awt.Color(255, 150, 200));
        jButtonStats.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonStats.setForeground(new java.awt.Color(255, 250, 100));
        jButtonStats.setMnemonic('s');
        jButtonStats.setText("Estadísticas");
        jButtonStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStatsActionPerformed(evt);
            }
        });

        jButtonReset.setBackground(new java.awt.Color(255, 150, 200));
        jButtonReset.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonReset.setForeground(new java.awt.Color(255, 250, 100));
        jButtonReset.setMnemonic('r');
        jButtonReset.setText("Restablecer");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jButtonMejoras.setBackground(new java.awt.Color(255, 150, 200));
        jButtonMejoras.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jButtonMejoras.setForeground(new java.awt.Color(255, 250, 100));
        jButtonMejoras.setMnemonic('u');
        jButtonMejoras.setText("Mejoras");
        jButtonMejoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMejorasActionPerformed(evt);
            }
        });

        jLabelCont.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N
        jLabelCont.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel1.setText("Tu comida favorita:");

        jButtonAyuda.setBackground(new java.awt.Color(255, 150, 200));
        jButtonAyuda.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonAyuda.setForeground(new java.awt.Color(255, 250, 100));
        jButtonAyuda.setMnemonic('h');
        jButtonAyuda.setText("Ayuda");
        jButtonAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jComboBoxUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelClicker, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCont, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonStats, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                    .addComponent(jButtonMejoras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelClicker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelCont, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addComponent(jButtonMejoras, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonStats, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setClickerImage(String item) {
        switch (item) {
            case "Pizzas" ->
                jLabelClicker.setIcon(new javax.swing.ImageIcon("src" + File.separator
                        + "main" + File.separator
                        + "java" + File.separator
                        + "com" + File.separator
                        + "mycompany" + File.separator
                        + "proyectotarea1" + File.separator
                        + "imgs" + File.separator
                        + "pizza.png"));
            case "Tartas" ->
                jLabelClicker.setIcon(new javax.swing.ImageIcon("src" + File.separator
                        + "main" + File.separator
                        + "java" + File.separator
                        + "com" + File.separator
                        + "mycompany" + File.separator
                        + "proyectotarea1" + File.separator
                        + "imgs" + File.separator
                        + "tarta.png"));
            default ->
                jLabelClicker.setIcon(new javax.swing.ImageIcon("src" + File.separator
                        + "main" + File.separator
                        + "java" + File.separator
                        + "com" + File.separator
                        + "mycompany" + File.separator
                        + "proyectotarea1" + File.separator
                        + "imgs" + File.separator
                        + "galleta.png"));
        }
    }

    private void producir() {
        Timer = new javax.swing.Timer(1000, e -> {
            synchronized (PantallaPrincipal.this) {
                this.cont += cps;
            }
            actualizarCont();
        });
        Timer.setRepeats(true);
        Timer.start();
    }

    /**
     * Devuelve el tiempo transcurrido en milisegundos desde el inicio del
     * juego.
     *
     * @return milisegundos transcurridos.
     */
    public long getCrono() {
        return System.currentTimeMillis() - cronoInicio;
    }

    /**
     * Formatea el tiempo de juego en formato HH:MM:SS.
     *
     * @return cadena con el tiempo formateado.
     */
    public String getCronometro() {
        long ms = getCrono();
        long segundos = ms / 1000;
        long hrs = segundos / 3600;
        long mins = (segundos % 3600) / 60;
        long segs = segundos % 60;
        return String.format("%02d:%02d:%02d", hrs, mins, segs);
    }

    /**
     * Unidad (tipo de producto) actualmente seleccionada.
     *
     * @return nombre de la unidad.
     */
    public String getUd() {
        return jComboBoxUnidad.getSelectedItem().toString();
    }

    // Setters y getters de variables declaradas manualmente
    /**
     * Contador total de unidades obtenidas.
     */
    public synchronized int getCont() {
        return cont;
    }

    /**
     * Fija el contador total.
     *
     * @param cont nuevo valor
     */
    public synchronized void setCont(int cont) {
        this.cont = cont;
    }

    /**
     * Intenta realizar una compra consumiendo unidades.
     *
     * @param precio coste en unidades.
     * @return true si se pudo comprar, false en caso contrario.
     */
    public synchronized boolean comprar(int precio) {
        if (this.cont >= precio) {
            this.cont -= precio;
            actualizarCont();
            return true;
        } else {
            return false;
        }

    }

    /**
     * Actualiza la etiqueta de la unidad (singular/plural).
     */
    public synchronized void actualizarUd() {
        if (cont == 1) {
            jLabelUnidad.setText(getUd().replace('s', ' '));
        } else {
            jLabelUnidad.setText(getUd());
        }
    }

    /**
     * Actualiza la etiqueta del contador y la unidad asociada.
     */
    public synchronized void actualizarCont() {
        jLabelCont.setText(String.valueOf(cont));
        actualizarUd();
    }

    private void jLabelClickerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClickerMouseEntered
        jLabelClicker.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabelClickerMouseEntered

    private void jLabelClickerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClickerMouseExited
        jLabelClicker.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabelClickerMouseExited

    private void jComboBoxUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUnidadActionPerformed
        setClickerImage(jComboBoxUnidad.getSelectedItem().toString());
        actualizarUd();
    }//GEN-LAST:event_jComboBoxUnidadActionPerformed

    private void jLabelClickerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelClickerMouseClicked
        this.cont += 1 + this.producitividad;
        actualizarCont();
    }//GEN-LAST:event_jLabelClickerMouseClicked

    private void jButtonMejorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMejorasActionPerformed
        PantallaMejoras mejoras = new PantallaMejoras(this);
        mejoras.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        mejoras.setVisible(true);
    }//GEN-LAST:event_jButtonMejorasActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        int resultado = JOptionPane.showConfirmDialog(this, "ATENCIÓN: Se reiniciarán las mejoras y " + getUd().toLowerCase() + " adquiridas a 0."
                + "\n¿Seguro que deseas continuar?", "Reinicio del juego", JOptionPane.YES_NO_OPTION);
        if (resultado == JOptionPane.YES_OPTION) {
            reset();
            incrementarResets();
            JOptionPane.showMessageDialog(this, "Y así, el mundo volvió a sus orígenes...", "Reinicio realizado", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStatsActionPerformed
        PantallaStats estadisticas = new PantallaStats(this);
        estadisticas.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        estadisticas.setVisible(true);
    }//GEN-LAST:event_jButtonStatsActionPerformed

    private void jButtonReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReset1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReset1ActionPerformed

    private void jButtonAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAyudaActionPerformed
        PantallaAyuda ayuda = new PantallaAyuda(this);
        ayuda.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        ayuda.setVisible(true);
    }//GEN-LAST:event_jButtonAyudaActionPerformed

    /**
     * Productividad adicional por clic.
     */
    public int getProducitividad() {
        return producitividad;
    }

    /**
     * Establece la productividad por clic.
     */
    public void setProducitividad(int producitividad) {
        this.producitividad = producitividad;
    }

    /**
     * Incrementa en 1 la productividad por clic.
     */
    public void incrementarProductividad() {
        producitividad++;
    }

    /**
     * Número de hornos comprados.
     */
    public int getHornos() {
        return hornos;
    }

    public void setHornos(int hornos) {
        this.hornos = hornos;
    }

    /**
     * Incrementa en 1 el número de hornos.
     */
    public void incrementarHornos() {
        hornos++;
    }

    /**
     * Número de fábricas compradas.
     */
    public int getFabricas() {
        return fabricas;
    }

    public void setFabricas(int fabricas) {
        this.fabricas = fabricas;
    }

    /**
     * Incrementa en 1 el número de fábricas.
     */
    public void incrementarFabricas() {
        fabricas++;
    }

    /**
     * Unidades por segundo generadas pasivamente.
     */
    public int getCps() {
        return cps;
    }

    public void setCps(int cps) {
        this.cps = cps;
    }

    /**
     * Incrementa la producción pasiva.
     *
     * @param suma cantidad a añadir.
     */
    public void incrementarCps(int suma) {
        this.cps += suma;
    }

    /**
     * Número de reinicios realizados.
     */
    public int getResets() {
        return resets;
    }

    public void setResets(int resets) {
        this.resets = resets;
    }

    /**
     * Incrementa en 1 el contador de reinicios.
     */
    public void incrementarResets() {
        resets++;
    }

    /**
     * Reestablece todas las mejoras y contadores a su valor inicial.
     */
    public synchronized void reset() {
        setCont(0);
        setProducitividad(0);
        setHornos(0);
        setFabricas(0);
        setCps(0);
        actualizarCont();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Crear y mostrar la ventana principal */
        java.awt.EventQueue.invokeLater(() -> new PantallaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAyuda;
    private javax.swing.JButton jButtonMejoras;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JButton jButtonReset1;
    private javax.swing.JButton jButtonStats;
    private javax.swing.JComboBox<String> jComboBoxUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelClicker;
    private javax.swing.JLabel jLabelCont;
    private javax.swing.JLabel jLabelUnidad;
    // End of variables declaration//GEN-END:variables
}
