/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectotarea1;

/**
 *
 * @author alumnadotarde
 */
public class PantallaMejoras extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaMejoras.class.getName());
    private final PantallaPrincipal principal;
    /**
     * Creates new form PantallaMejoras
     */
    public PantallaMejoras(PantallaPrincipal principal) {
        this.principal = principal;
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelProductividad = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelInfoProds = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelContProds = new javax.swing.JLabel();
        jButtonComprarProductividad = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelInfoHornos = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabelContHornos = new javax.swing.JLabel();
        jButtonComprarHorno = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabelInfoFabricas = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabelContFabricas = new javax.swing.JLabel();
        jButtonComprarFabrica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 0, 30, 10));

        jLabelProductividad.setIcon(new javax.swing.ImageIcon("/home/alumnadotarde/NetBeansProjects/ProyectoTarea1/src/main/java/com/mycompany/proyectotarea1/imgs/cursor.png")); // NOI18N
        jPanel1.add(jLabelProductividad);

        jPanel2.setLayout(new java.awt.GridLayout(2, 0));

        jLabelInfoProds.setText("Productividad - +1 "+principal.getUd().toLowerCase().replace('s', ' ')+"por clic");
        jPanel2.add(jLabelInfoProds);

        jPanel5.setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tienes:");
        jPanel5.add(jLabel1);

        jLabelContProds.setText(String.valueOf(principal.getProducitividad()));
        jPanel5.add(jLabelContProds);

        jPanel2.add(jPanel5);

        jPanel1.add(jPanel2);

        jButtonComprarProductividad.setText("Comprar (5 X)");
        jButtonComprarProductividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarProductividadActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonComprarProductividad);

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/alumnadotarde/NetBeansProjects/ProyectoTarea1/src/main/java/com/mycompany/proyectotarea1/imgs/horno.png")); // NOI18N
        jPanel1.add(jLabel2);

        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        jLabelInfoHornos.setText("Horno -  0.1 "+principal.getUd().toLowerCase()+" por seg.");
        jPanel3.add(jLabelInfoHornos);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tienes:");
        jPanel6.add(jLabel7);

        jLabelContHornos.setText(String.valueOf(principal.getHornos()));
        jPanel6.add(jLabelContHornos);

        jPanel3.add(jPanel6);

        jPanel1.add(jPanel3);

        jButtonComprarHorno.setText("Comprar (10 X)");
        jButtonComprarHorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarHornoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonComprarHorno);

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/alumnadotarde/NetBeansProjects/ProyectoTarea1/src/main/java/com/mycompany/proyectotarea1/imgs/fabrica.png")); // NOI18N
        jPanel1.add(jLabel3);

        jPanel4.setLayout(new java.awt.GridLayout(2, 0));

        jLabelInfoFabricas.setText("Fábrica - 5 "+principal.getUd().toLowerCase()+" por seg.");
        jPanel4.add(jLabelInfoFabricas);

        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Tienes:");
        jPanel7.add(jLabel10);

        jLabelContFabricas.setText(String.valueOf(principal.getFabricas()));
        jPanel7.add(jLabelContFabricas);

        jPanel4.add(jPanel7);

        jPanel1.add(jPanel4);

        jButtonComprarFabrica.setText("Comprar (20 X)");
        jButtonComprarFabrica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprarFabricaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonComprarFabrica);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void sincronizarUds() {
        jLabelInfoProds.setText("Productividad - +1 "+principal.getUd().toLowerCase().replace('s', ' ')+"por click.");
        jLabelInfoHornos.setText("Hornos - 5 "+principal.getUd().toLowerCase()+" por seg.");
        jLabelInfoFabricas.setText("Fábricas - 5 "+principal.getUd().toLowerCase()+" por seg.");
    }
    
    
    private void actualizarProd() {
        jLabelContProds.setText(String.valueOf(principal.getProducitividad()));
    }
    
    private void actualizarHornos() {
        jLabelContProds.setText(String.valueOf(principal.getHornos()));
    }
    
    private void actualizarFabricas() {
        jLabelContProds.setText(String.valueOf(principal.getProducitividad()));
    }
    
    private void jButtonComprarProductividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarProductividadActionPerformed
        if (principal.comprar(5)) {
            principal.incrementarProductividad();
            actualizarProd();
        }
    }//GEN-LAST:event_jButtonComprarProductividadActionPerformed

    private void jButtonComprarFabricaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarFabricaActionPerformed
        if (principal.comprar(20)) {
            principal.incrementarCps(5);
            principal.incrementarFabricas();
            actualizarFabricas();
        }
    }//GEN-LAST:event_jButtonComprarFabricaActionPerformed

    private void jButtonComprarHornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprarHornoActionPerformed
        if (principal.comprar(10)) {
            principal.incrementarCps(1);
            principal.incrementarHornos();
            actualizarHornos();
        }
    }//GEN-LAST:event_jButtonComprarHornoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new PantallaMejoras(principal).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonComprarFabrica;
    private javax.swing.JButton jButtonComprarHorno;
    private javax.swing.JButton jButtonComprarProductividad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelContFabricas;
    private javax.swing.JLabel jLabelContHornos;
    private javax.swing.JLabel jLabelContProds;
    private javax.swing.JLabel jLabelInfoFabricas;
    private javax.swing.JLabel jLabelInfoHornos;
    private javax.swing.JLabel jLabelInfoProds;
    private javax.swing.JLabel jLabelProductividad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables

}
